services:
  streamripper-SST:
    build:
      context: https://github.com/beamer2k23/docker-streamripper.git
      dockerfile: Dockerfile
    image: streamripper-sst:latest
    container_name: streamripper-SST
    restart: unless-stopped
    volumes:
      - /media/USB2GB/SST:/home/streamripper/destination
      - /media/DS500/SST:/home/streamripper/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
    environment:
      - STREAMRIPPERSERVER=http://hi5.streamingsoundtracks.com
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD-SHELL", "pidof streamripper || exit 1"]
      interval: 90s
      timeout: 10s
      retries: 2
      start_period: 30s
    labels:
      autoheal-app: true

  autoheal:
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
    image: willfarrell/autoheal:latest
    container_name: streamripper-autoheal
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock      
      
